name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [ "master" ] 
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "*/5 * * * *"
jobs:
  build:
    name: Run Web App 
    runs-on: ubuntu-latest
    if: github.event.schedule = schedule
    container:
      image: openjdk:8-jdk-slim
    steps:
      - run: echo "hello"
  testing:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: openjdk:8-jdk-slim
    steps:
      - run: |
          pwd
  calling:
    needs: build 
    runs-on: ubuntu-latest
    if: github.event.schedule = schedule
    container:
      image: openjdk:8-jdk-slim
    steps:
      - run: |
          ls -lrt
