name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [ "master" ] 
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    name: Run Web App
    runs-on: ubuntu-latest
    steps:
      - name: Build Web App 
        run: |
          echo "Build Web App test"
          sleep 10s
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: Npraveenreddy
          repo: back-end
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: testing.yml
          ref: main
      - name: Deploy Web App
        run: |
          echo "Deploy Web App"
          sleep 10s