name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [ "master" ] 
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    name: Run Web App
    runs-on: ubuntu-latest
    container:
      image: openjdk:8-jdk-slim
    steps:
      - name: Build Web App 
        run: |
          echo "Build Web App test"
          sleep 10s
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: Npraveenreddy
          repo: back-end
          inputs: (github.ref == 'workflow_dispatch' || github.ref == 'refs/heads/master')
          # if: (!($CI_COMMIT_MESSAGE =~ /^\[.github/workflows/testing.yml\].*/) || ${{ github.event_name }} == "push" && ${{ github.ref }} == "master")
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: testing.yml
          ref: master
      - name: Deploy Web App
        run: |
          echo "Deploy Web App"
          sleep 10s