name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [ "master" ] 
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "*/5 * * * *"
jobs:
  build:
    name: Run Web App 
    runs-on: ubuntu-latest
    if: github.event.schedule = schedule
    container:
      image: openjdk:8-jdk-slim
    steps:
      - name: Build Web App 
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: Npraveenreddy
          repo: back-end
          workflow_file_name: testing.yml
          ref: master
  testing:
    needs: build
    name: echo the word  
    runs-on: ubuntu-latest
    container:
      image: openjdk:8-jdk-slim
    steps:
      - run: |
          pwd
  calling:
    needs: build
    name: listing  
    runs-on: ubuntu-latest
    if: github.event.schedule = schedule
    container:
      image: openjdk:8-jdk-slim
    steps:
      - run: |
          ls -lrt
