name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [ "master" ] 
  pull_request:
    branches: [ "master" ]
jobs:
  trigger_downstream:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Your Service
      uses: adityakar/workflow-dispatcher@v1
      with:
        owner: Npraveenreddy
        repo: back-end
        token: ${{ secrets.G_ACCESS_TOKEN }}
        event_type: deploytest
        client_payload: '{"git-ref": "${{ github.event.inputs.git-ref }}"}'

  # build:
  #   name: Run Web App
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Build Web App 
  #       run: |
  #         echo "Build Web App test"
  #         sleep 10s
  #     - uses: convictional/trigger-workflow-and-wait@v1.3.0
  #       with:
  #         owner: Npraveenreddy
  #         repo: back-end
  #         github_token: ${{ secrets.G_ACCESS_TOKEN }}
  #         workflow_file_name: testing.yml
  #         ref: master
  #         event_type: deploytest
  #         client_payload: '{"git-ref": "${{ github.event.inputs.git-ref }}"}'
  #     - name: Deploy Web App
  #       run: |
  #         echo "Deploy Web App"
  #         sleep 10s