name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [ "master" ] 
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "*/5 * * * *"
jobs:
  build:
    
    name: Run Web App 
    runs-on: ubuntu-latest
    container:
      image: openjdk:8-jdk-slim
    steps:
    
      - run: echo "hello"

